[build]
builder = "nixpacks"

[phases.install]
cmds = [
  "pip install --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt",
  "pip uninstall -y opencv-python opencv-contrib-python || true"
]
